### ISSUE TITLE
Where is start 

### ISSUE THREAD

**Issue by MDALEY2964** [Thinkright20/IP-Finder#2]
Please describe in detail WHERE START IS..U SAID PLACE LINK IN START. BUT DIDNT SHOW WHERE THAT IS...
THE LINK INDEX.JS. DOES NOT DELETE OR ERASE..SO WHERE IS START PLEASE....NEED HELP..

BEEN DOIN FOR HOURS AS U CAN SEE N NEED SO I CAN BREATH N SURVIVE ..CAN U HELP...WHERE IS THE START U MENTION TO PUT 1 OF 3 OR ALL 3 LINKS INTO...WHOCH ..WHERE WHAT BROWSER ???????

**Comment by Thinkright20** [comment]
The start button is at the top of the repl, it will be Green, and with a Play Button beside it.

The link stuff was for you to know how to format it. The format looks something like this: https://MYREPLNAME.MYREPLUSERNAME.repl.co

Hope this helped :D
